### ISSUE TITLE
No module named 'mcoding_youtube'`

### ISSUE THREAD

**Issue by RaphaelS-git** [mCodingLLC/mCodingYouTube#1]
Hey,
I watch the Youtube Video and trying to set it up for my own channel.

I start having problems with running the download_single_video_data.py file.
By running the python file I get following error: 

`ModuleNotFoundError: No module named 'mcoding_youtube'`

What is the problem here and how can I fix that?

**Comment by mCodingLLC** [comment]
You need to make sure the `mcoding_youtube` folder is in your path, either by adding the parent directory to your `sys.path` (happens automatically if you are using Pycharm and click the green "run" array) or by running your script from the parent directory, e.g. `python ./scripts/download_single_video_data.py`
